"""empty message

Revision ID: e0d3a3b30ec0
Revises: a0028205d7f2
Create Date: 2022-11-19 10:30:30.935217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d3a3b30ec0'
down_revision = 'a0028205d7f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk__transactions__currency_account_id__currency', 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk__transactions__currency_account_id__currency_account'), 'transactions', 'currency_account', ['currency_account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__transactions__currency_account_id__currency_account'), 'transactions', type_='foreignkey')
    op.create_foreign_key('fk__transactions__currency_account_id__currency', 'transactions', 'currency', ['currency_account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
