"""empty message

Revision ID: 7c642e54d680
Revises: 5de40a7e6fe8
Create Date: 2022-11-19 03:38:56.802635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c642e54d680'
down_revision = '5de40a7e6fe8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__currency')),
    sa.UniqueConstraint('id', name=op.f('uq__currency__id')),
    sa.UniqueConstraint('name', name=op.f('uq__currency__name'))
    )
    op.create_table('news',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__news')),
    sa.UniqueConstraint('id', name=op.f('uq__news__id'))
    )
    op.create_table('currency_account',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('currency_id', postgresql.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], name=op.f('fk__currency_account__currency_id__currency'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__currency_account__user_id__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__currency_account')),
    sa.UniqueConstraint('id', name=op.f('uq__currency_account__id'))
    )
    op.create_table('transactions',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('currency_account_id', postgresql.UUID(), nullable=False),
    sa.Column('change_value', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['currency_account_id'], ['currency.id'], name=op.f('fk__transactions__currency_account_id__currency'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__transactions')),
    sa.UniqueConstraint('id', name=op.f('uq__transactions__id'))
    )
    op.create_unique_constraint(op.f('uq__users__id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__id'), 'users', type_='unique')
    op.drop_table('transactions')
    op.drop_table('currency_account')
    op.drop_table('news')
    op.drop_table('currency')
    # ### end Alembic commands ###
