"""empty message

Revision ID: a0028205d7f2
Revises: c04481b855bd
Create Date: 2022-11-19 10:08:59.270984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0028205d7f2'
down_revision = 'c04481b855bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_account', sa.Column('value', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency_account', 'value')
    # ### end Alembic commands ###
