name: MyDeploy

on:
  push:
    branches:
      - main

jobs:
  MakeEnvFile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      run: >
        touch .env
        echo FASTAPI_HASH_ALGORITHM=${{ secrets.FASTAPI_HASH_ALGORITHM }} >> .env
        cat .env

  Prepare:
    runs-on: ubuntu-latest
    needs: [MakeEnvFile]
    steps:
      - uses: actions/checkout@v2
      - run: make prepare

  Services:
    runs-on: ubuntu-latest
    needs: [Prepare]
    steps:
      - uses: actions/checkout@v2
      - run: make services

  Run:
    runs-on: ubuntu-latest
    needs: [Services]
    steps:
      - uses: actions/checkout@v2
      - run: make run