name: MyDeploy

on:
  push:
    branches:
      - main

jobs:
  Prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: touch private_key && echo -e "${{ secrets.ssh_key }}" > private_key
      - run: chmod 600 private_key
      - run: ssh -i private_key -o StrictHostKeyChecking=accept-new deployer@92.63.102.99 "cd test23; git pull"
      - run: ssh -i private_key deployer@92.63.102.99 "touch .env; echo -e ${{ secrets.prikol }} > .env"
      - run: make prepare

  Services:
    runs-on: ubuntu-latest
    needs: [Prepare]
    steps:
      - uses: actions/checkout@v2
      - run: touch .env && echo -e ${{ secrets.prikol }} > .env
      - run: make services

  Run:
    runs-on: ubuntu-latest
    needs: [Services]
    steps:
      - uses: actions/checkout@v2
      - run: touch .env && echo -e ${{ secrets.prikol }} > .env
      - run: make run