name: MyDeploy

on:
  push:
    branches:
      - main

jobs:
  Prepare:
    runs-on: ubuntu-latest
    needs: [MakeEnvFile]
    steps:
      - uses: actions/checkout@v2
      - run: touch .env
      - run: echo FASTAPI_HASH_ALGORITHM=${{ secrets.FASTAPI_HASH_ALGORITHM }} >> .env
      - run: cat .env
      - run: make prepare

  Services:
    runs-on: ubuntu-latest
    needs: [Prepare]
    steps:
      - uses: actions/checkout@v2
      - run: make services

  Run:
    runs-on: ubuntu-latest
    needs: [Services]
    steps:
      - uses: actions/checkout@v2
      - run: make run