name: first-github-action

on:
  push:
    branches:
      - main

jobs:
  stages:
    - build
      prepare:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: make prepare
    - services
      prepare:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: make services
    - run_project
      prepare:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: make run
