name: first-github-action

on:
  push:
    branches:
      - main
stages:
  - build
  - test
 
build the car:
  stage: build
  script:
    - echo "Build"
 
test the car:
  stage: test
  script:
    - echo "Test"