name: first-github-action

on:
  push:
    branches:
      - main

jobs:
  uses: actions/checkout@v2
  prepare:
    runs-on: ubuntu-latest
    steps:    
      - run: make prepare
  services:
    runs-on: ubuntu-latest
    steps:    
      - run: make services
  run_project:
    runs-on: ubuntu-latest
    steps:    
      - run: make run
