name: MyDeploy

on:
  push:
    branches:
      - main

jobs:
  Prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: touch .env && echo -e ${{ secrets.prikol }} > .env
      - run: make prepare

  Services:
    runs-on: ubuntu-latest
    needs: [Prepare]
    steps:
      - uses: actions/checkout@v2
      - run: touch .env && echo -e ${{ secrets.prikol }} > .env
      - run: make services

  Run:
    runs-on: ubuntu-latest
    needs: [Services]
    steps:
      - uses: actions/checkout@v2
      - run: touch .env && echo -e ${{ secrets.prikol }} > .env
      - run: make run